language: generic 
sudo : required
services:
  - docker

before_install:
  - docker build -t shivam/deploy-with-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true shivam/deploy-with-docker  npm run test -- --coverage